### ISSUE TITLE
Stuck after submitting invalid form

### ISSUE THREAD

**Issue by stefanjudis** [contentful-labs/file-upload-example#2]
The form is missing some validation rules and can be submitted without set values. After seeing an error modal the user is stuck and can't get out of the loading state anymore (invalid values sit in localstorage).

Just an idea – maybe we could also add a link to the github repo for convenience and a link to CTF docu. People coming from Preact don't know how to deal with this. :)

![fileupload](https://cloud.githubusercontent.com/assets/962099/24362725/e97f9354-130d-11e7-8ec2-d303ab2968ca.gif)

**Comment by Khaledgarbaya** [comment]
@stefanjudis yep the form validation needs some work, for now you can clear the `localstorage`

**Comment by Khaledgarbaya** [comment]
fixed in https://github.com/contentful-labs/file-upload-example/pull/4
